[
    { firstName: "Raj", lastName: "Ankathi", userName: "Raj Anakthi", avatar: "doraemon.jpg" },
    { firstName: "Raj", lastName: "Ankathi", userName: "Raj Anakthi2", avatar: "doraemon.jpg" },
    { firstName: "Raj", lastName: "Ankathi", userName: "Raj Anakthi", avatar: "doraemon.jpg" },
    { firstName: "Raj", lastName: "Ankathi", userName: "Raj Anakthi2", avatar: "doraemon.jpg" },
    { firstName: "Raj", lastName: "Ankathi", userName: "Raj Anakthi", avatar: "doraemon.jpg" },
    { firstName: "Raj", lastName: "Ankathi", userName: "Raj Anakthi2", avatar: "doraemon.jpg" },
    { firstName: "Raj", lastName: "Ankathi", userName: "Raj Anakthi", avatar: "doraemon.jpg" },
    { firstName: "Raj", lastName: "Ankathi", userName: "Raj Anakthi2", avatar: "doraemon.jpg" },
    { firstName: "Raj", lastName: "Ankathi", userName: "Raj Anakthi", avatar: "doraemon.jpg" },
    { firstName: "Raj", lastName: "Ankathi", userName: "Raj Anakthi2", avatar: "doraemon.jpg" },
    { firstName: "Raj", lastName: "Ankathi", userName: "Raj Anakthi", avatar: "doraemon.jpg" },
    { firstName: "Raj", lastName: "Ankathi", userName: "Raj Anakthi2", avatar: "doraemon.jpg" },
    { firstName: "Raj", lastName: "Ankathi", userName: "Raj Anakthi", avatar: "doraemon.jpg" },
    { firstName: "Raj", lastName: "Ankathi", userName: "Raj Anakthi2", avatar: "doraemon.jpg" },
    { firstName: "Raj", lastName: "Ankathi", userName: "Raj Anakthi", avatar: "doraemon.jpg" },
    { firstName: "Raj", lastName: "Ankathi", userName: "Raj Anakthi2", avatar: "doraemon.jpg" },
    { firstName: "Raj", lastName: "Ankathi", userName: "Raj Anakthi", avatar: "doraemon.jpg" },
    { firstName: "Raj", lastName: "Ankathi", userName: "Raj Anakthi2", avatar: "doraemon.jpg" }
];
[
    { id: 1, firstName: "Raj", lastName: "Ankathi", userName: "Raj Anakthi", avatar: "doraemon.jpg" },
    { id: 2, firstName: "Raj", lastName: "Ankathi", userName: "Raj Anakthi2", avatar: "doraemon.jpg" },
    { id: 3, firstName: "Raj", lastName: "Ankathi", userName: "Raj Anakthi", avatar: "doraemon.jpg" },
    { id: 4, firstName: "Raj", lastName: "Ankathi", userName: "Raj Anakthi2", avatar: "doraemon.jpg" },
    { id: 5, firstName: "Raj", lastName: "Ankathi", userName: "Raj Anakthi", avatar: "doraemon.jpg" },
    { id: 6, firstName: "Raj", lastName: "Ankathi", userName: "Raj Anakthi2", avatar: "doraemon.jpg" },
    { id: 7, firstName: "Raj", lastName: "Ankathi", userName: "Raj Anakthi", avatar: "doraemon.jpg" },
    { id: 8, firstName: "Raj", lastName: "Ankathi", userName: "Raj Anakthi2", avatar: "doraemon.jpg" },
    { id: 9, firstName: "Raj", lastName: "Ankathi", userName: "Raj Anakthi", avatar: "doraemon.jpg" },
    { id: 10, firstName: "Raj", lastName: "Ankathi", userName: "Raj Anakthi2", avatar: "doraemon.jpg" },
    { id: 11, firstName: "Raj", lastName: "Ankathi", userName: "Raj Anakthi", avatar: "doraemon.jpg" },
    { id: 12, firstName: "Raj", lastName: "Ankathi", userName: "Raj Anakthi2", avatar: "doraemon.jpg" },
    { id: 13, firstName: "Raj", lastName: "Ankathi", userName: "Raj Anakthi", avatar: "doraemon.jpg" },
    { id: 14, firstName: "Raj", lastName: "Ankathi", userName: "Raj Anakthi2", avatar: "doraemon.jpg" },
    { id: 15, firstName: "Raj", lastName: "Ankathi", userName: "Raj Anakthi", avatar: "doraemon.jpg" },
    { id: 16, firstName: "Raj", lastName: "Ankathi", userName: "Raj Anakthi2", avatar: "doraemon.jpg" },
];
//# sourceMappingURL=userdata.js.map